<a href="https://colab.research.google.com/github/Jiadia22/2025-AI-Application-Practice/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy

In [ ]:
import numpy as np
array = np.array([1,4,5,6],float)

In [ ]:
array

array([1., 4., 5., 6.])

In [ ]:
testlist = [[1,4,5,8],[1,4,5]] # 2차원
testlist

[[1, 4, 5, 8], [1, 4, 5]]

In [ ]:
np.array(testlist,float) #2차원 잘 지원 안 함, 사실은 위에 크기 맞춰줘야함.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
type(array[3])

numpy.float64

3. 배열의 생성

In [ ]:
test_array = np.array([1,3,5,'8'],float)
test_array

array([1., 3., 5., 8.])

In [ ]:
test_array.dtype

dtype('float64')

In [ ]:
test_array.shape

(4,)

In [ ]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
matrix

[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]

In [ ]:
np.array(matrix,int).shape

(3, 4)

In [ ]:
rank3 = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(rank3,int).shape

(4, 3, 4)

In [ ]:
np.array(rank3,int).ndim

3

In [ ]:
np.array(rank3,int).size

48

In [ ]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=int) # 정수부분만 출력

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [ ]:
import sys
np.array([[1,2,3.5],[4,5,6.5]],dtype=np.float32).itemsize #itemsize는 원소 하나당 바이트 단위

4

In [ ]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=np.float64).itemsize

8

4.배열의 구조 다루기

In [ ]:
x = np.array([[1,2,5,8],[1,2,5,8]])
x

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
x.shape

(2, 4)

In [ ]:
x.reshape(-1)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [ ]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

인덱싱과 슬라이싱

In [ ]:
x = np.array([[1,2,3],[4.5,5,6]],int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x[0]

array([1, 2, 3])

In [ ]:
x[0][0]

np.int64(1)

In [ ]:
x[0,0]

np.int64(1)

In [ ]:
x[0,2]=100

In [ ]:
x

array([[  1,   2, 100],
       [  4,   5,   6]])

In [ ]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
x = np.array(range(15),int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
x[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [ ]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

배열생성함수

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [ ]:
range(10) #배열은 아님

range(0, 10)

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
range(0,5)

range(0, 5)

In [ ]:
for i in range(0,5,0.5): #for문은 정수형만
  print(i)

TypeError: 'float' object cannot be interpreted as an integer

ones,zeros,empty

In [ ]:
np.ones(shape=(5,2),dtype = np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [ ]:
np.zeros(shape=(2,2),dtype = np.float32).itemsize

4

In [ ]:
np.empty(shape=(2,4),dtype=np.float32) #쓰레기

array([[0.    , 1.875 , 0.    , 2.125 ],
       [0.    , 2.3125, 0.    , 2.5   ]], dtype=float32)

In [ ]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.ones_like(x) #x의 shape와 dtype를 사용

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.empty_like(x)

array([[102848622,         0,         0,         0],
       [        0,         0,         0,         0],
       [        0,         0,         0,         0]])

In [ ]:
np.identity(n=3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.identity(n=5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.eye(N=3,M=5,k=2) #k부터 시작하는 단위행

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.diag(matrix)

array([0, 4, 8])

In [ ]:
np.diag(matrix,k=1)

array([1, 5])

통계 분석 함수

In [ ]:
np.random.uniform(0,5,10) #0부터 5사이 10개

array([4.22960285, 4.33275735, 3.77822191, 4.11319619, 4.70206859,
       1.93087503, 2.55032486, 4.28876072, 1.66940052, 4.80882913])

In [ ]:
np.random.normal(0,2,10) #평균이 0이고 분산이 2인 10개

array([-0.54928624, -0.63268018, -2.35424157, -3.95296055, -3.27335913,
        1.82683473,  1.02444837, -2.37965778,  1.83066566, -0.21305096])

넘파이배열 연산

In [ ]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
test_array.sum()

np.int64(55)

In [ ]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
test_array.sum(axis=1)

array([10, 26, 42])

In [ ]:
test_array.mean(axis=1) #numpy배열용

array([ 2.5,  6.5, 10.5])

In [ ]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [ ]:
np.mean(test_array,axis=1) #리스트로도 쓸 수 있음

array([ 2.5,  6.5, 10.5])

연결 함수

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2)) #vertical

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((v1,v2)) #horizontal

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((v2,v1))

array([4, 5, 6, 1, 2, 3])

In [ ]:
v1=v1.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [ ]:
v2=v2.reshape(-1,1)
v2

array([[4],
       [5],
       [6]])

In [ ]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.concatenate((v1,v2),axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
v1=np.array([1,2,3,4]).reshape(2,2)
v1

array([[1, 2],
       [3, 4]])

In [ ]:
v2 = np.array([[5,6]]).T
v2

array([[5],
       [6]])

In [ ]:
np.concatenate((v1,v2),axis=1) #가로로 붙는

array([[1, 2, 5],
       [3, 4, 6]])

3차시 사칙연산 함수

In [ ]:
x = np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x+x #x+2, x-x, x/x, x**2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
x1 = np.arange(1,7).reshape(2,3)
x2 = np.arange(1,7).reshape(3,2)
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x1.dot(x2)

array([[22, 28],
       [49, 64]])

In [ ]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x+10 # 브로드캐스팅 -, //, **, %

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [ ]:
x+v #브로드캐스

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

비교연산과 데이터 추출

In [ ]:
x = np.array([4,3,2,6,8])
x>3

array([ True, False, False,  True,  True])

In [ ]:
x = np.array([1,3,0])
y = np.array([2,1,7])
x>y

array([False,  True, False])

In [ ]:
(x>3).all()

np.False_

In [ ]:
(x>3).any() #3과의 비교도 브로드캐스팅적으로 비교한 것임

np.False_

In [ ]:
x = np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [ ]:
np.where(x>5)

(array([1, 2]),)

In [ ]:
np.where(x>5,10,20) #참일경우에10, 거짓이면20

array([20, 10, 10, 20, 20])

In [ ]:
x

array([4, 6, 7, 3, 2])

In [ ]:
np.argsort(x)

array([4, 3, 0, 1, 2])

In [ ]:
np.argmax(x)

np.int64(2)

In [ ]:
np.argmin(x)

np.int64(4)

인덱스를 활용한 데이터 추출

In [ ]:
x

array([4, 6, 7, 3, 2])

In [ ]:
cond = x>3

In [ ]:
cond

array([ True,  True,  True, False, False])

In [ ]:
x[cond]

array([4, 6, 7])

In [ ]:
x.shape

(5,)

In [ ]:
cond.shape

(5,)

In [ ]:
cond = np.array([1,2,0,2,2,2],int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [ ]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])