<a href="https://colab.research.google.com/github/Jiadia22/2025-AI_Application/blob/main/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/drive/MyDrive/Datazip/week13/car.csv")
data

name  year  selling_price  km_driven    fuel  \
0           Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1     Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2         Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3        Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4           Maruti Swift VXI BSIII  2007         130000     120000  Petrol   
...                            ...   ...            ...        ...     ...   
8123             Hyundai i20 Magna  2013         320000     110000  Petrol   
8124         Hyundai Verna CRDi SX  2007         135000     119000  Diesel   
8125        Maruti Swift Dzire ZDi  2009         382000     120000  Diesel   
8126               Tata Indigo CR4  2013         290000      25000  Diesel   
8127               Tata Indigo CR4  2013         290000      25000  Diesel   

     seller_type transmission                 owner     mileage   engine  \
0     Individual       Manual           First Owner   23.4 kmpl  1248 CC   
1     Individual       Manual          Second Owner  21.14 kmpl  1498 CC   
2     Individual       Manual           Third Owner   17.7 kmpl  1497 CC   
3     Individual       Manual           First Owner   23.0 kmpl  1396 CC   
4     Individual       Manual           First Owner   16.1 kmpl  1298 CC   
...          ...          ...                   ...         ...      ...   
8123  Individual       Manual           First Owner   18.5 kmpl  1197 CC   
8124  Individual       Manual  Fourth & Above Owner   16.8 kmpl  1493 CC   
8125  Individual       Manual           First Owner   19.3 kmpl  1248 CC   
8126  Individual       Manual           First Owner  23.57 kmpl  1396 CC   
8127  Individual       Manual           First Owner  23.57 kmpl  1396 CC   

       max_power                     torque  seats  
0         74 bhp             190Nm@ 2000rpm    5.0  
1     103.52 bhp        250Nm@ 1500-2500rpm    5.0  
2         78 bhp      12.7@ 2,700(kgm@ rpm)    5.0  
3         90 bhp   22.4 kgm at 1750-2750rpm    5.0  
4       88.2 bhp      11.5@ 4,500(kgm@ rpm)    5.0  
...          ...                        ...    ...  
8123   82.85 bhp           113.7Nm@ 4000rpm    5.0  
8124     110 bhp  24@ 1,900-2,750(kgm@ rpm)    5.0  
8125    73.9 bhp             190Nm@ 2000rpm    5.0  
8126      70 bhp        140Nm@ 1800-3000rpm    5.0  
8127      70 bhp        140Nm@ 1800-3000rpm    5.0  

[8128 rows x 13 columns]

In [4]:
data.info() #밑에는 결측치 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [5]:
round(data.describe(),2) #아웃라이어 확인 min 이 1

year  selling_price   km_driven    seats
count  8128.00        8128.00     8128.00  7907.00
mean   2013.80      638271.81    69819.51     5.42
std       4.04      806253.40    56550.55     0.96
min    1983.00       29999.00        1.00     2.00
25%    2011.00      254999.00    35000.00     5.00
50%    2015.00      450000.00    60000.00     5.00
75%    2017.00      675000.00    98000.00     5.00
max    2020.00    10000000.00  2360457.00    14.00

In [9]:
data['engine'].str.split(expand=True)

0
0     1248
1     1498
2     1497
3     1396
4     1298
...    ...
8123  1197
8124  1493
8125  1248
8126  1396
8127  1396

[8128 rows x 1 columns]

In [8]:
data[['engine','engine_unit']] = data['engine'].str.split(expand=True)

In [12]:
data['engine'].head()

0    1248
1    1498
2    1497
3    1396
4    1298
Name: engine, dtype: object

In [11]:
data['engine_unit'].head()

0    CC
1    CC
2    CC
3    CC
4    CC
Name: engine_unit, dtype: object

In [13]:
data['engine']=data['engine'].astype('float32')

In [14]:
data['engine'].head()

0    1248.0
1    1498.0
2    1497.0
3    1396.0
4    1298.0
Name: engine, dtype: float32

In [15]:
data['engine_unit'].unique()

array(['CC', nan], dtype=object)

In [16]:
data.drop('engine_unit',axis=1,inplace=True)

In [17]:
data[['max_power','max_power_unit']] = data['max_power'].str.split(expand=True)

In [18]:
data['max_power'].head()

0        74
1    103.52
2        78
3        90
4      88.2
Name: max_power, dtype: object

In [20]:
data['max_power'] = data['max_power'].astype('float32')

ValueError: could not convert string to float: 'bhp'

In [22]:
data[data['max_power']=='bhp']

name  year  selling_price  km_driven fuel seller_type  \
4933  Maruti Omni CNG  2000          80000     100000  CNG  Individual   

     transmission         owner     mileage  engine max_power torque  seats  \
4933       Manual  Second Owner  10.9 km/kg   796.0       bhp    NaN    8.0   

     max_power_unit  
4933           None

In [27]:
def isFloat(value):
  try:
    num = float(value)
    return num
  except ValueError:
    return np.nan

In [28]:
data['max_power'] = data['max_power'].apply(isFloat)

In [30]:
data['max_power'].head()

0     74.00
1    103.52
2     78.00
3     90.00
4     88.20
Name: max_power, dtype: float64

In [29]:
data['max_power_unit'].unique()

array(['bhp', nan, None], dtype=object)

In [31]:
data.drop('max_power_unit',axis = 1,inplace=True)

In [32]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage  engine  max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248.0      74.00   
1  Individual       Manual  Second Owner  21.14 kmpl  1498.0     103.52   
2  Individual       Manual   Third Owner   17.7 kmpl  1497.0      78.00   
3  Individual       Manual   First Owner   23.0 kmpl  1396.0      90.00   
4  Individual       Manual   First Owner   16.1 kmpl  1298.0      88.20   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [33]:
data[['mileage','mileage_unit']]=data['mileage'].str.split(expand=True)

In [34]:
data['mileage'] = data['mileage'].astype('float32')

In [35]:
data['mileage_unit'].unique() #단위가 다름

array(['kmpl', 'km/kg', nan], dtype=object)

In [36]:
data['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [ ]:
#petrol 리터당 $40.43
#Diesel 리터당 $73.45
#LPG 킬로그램당 $40.85
#CNG 킬로그램당 $44.23

In [37]:
def mile(x):
  if x['fuel'] == 'Petrol':
    return x['mileage']/80.43
  elif x['fuel'] == 'Diesel':
    return x['mileage']/73.56
  elif x['fuel'] == 'LPG':
    return x['mileage']/40.85
  else:
    return x['mileage']/44.23

In [38]:
data['mileage'] = data.apply(mile,axis=1)

In [39]:
data.drop('mileage_unit',axis = 1,inplace=True)

In [41]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage  engine  max_power  \
0  Individual       Manual   First Owner  0.318108  1248.0      74.00   
1  Individual       Manual  Second Owner  0.287384  1498.0     103.52   
2  Individual       Manual   Third Owner  0.220067  1497.0      78.00   
3  Individual       Manual   First Owner  0.312670  1396.0      90.00   
4  Individual       Manual   First Owner  0.200174  1298.0      88.20   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

결측치 처리와 더미 변수 변환

In [42]:
data['torque'].head()

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: object

In [44]:
data['torque'] = data['torque'].str.upper()

In [45]:
def torque_unit(x):
  if 'NM' in str(x):
    return 'Nm'
  elif 'KGM' in str(x):
    return 'kgm'

In [46]:
data['torque_unit'] = data['torque'].apply(torque_unit)

In [47]:
data['torque_unit'].unique()

array(['Nm', 'kgm', None], dtype=object)

In [50]:
data[data['torque_unit'].isna()]

name  year  selling_price  km_driven  \
13                    Maruti Swift 1.3 VXi  2007         200000      80000   
31                      Fiat Palio 1.2 ELX  2003          70000      50000   
78                         Tata Indica DLS  2003          50000      70000   
87             Maruti Swift VDI BSIV W ABS  2015         475000      78000   
119                  Maruti Swift VDI BSIV  2010         300000     120000   
...                                    ...   ...            ...        ...   
7846                Toyota Qualis Fleet A3  2000         200000     100000   
7996             Hyundai Santro LS zipPlus  2000         140000      50000   
8009  Hyundai Santro Xing XS eRLX Euro III  2006         145000      80000   
8068             Ford Figo Aspire Facelift  2017         580000     165000   
8103                  Maruti Swift 1.3 VXi  2006         130000     100000   

        fuel seller_type transmission         owner  mileage  engine  \
13    Petrol  Individual       Manual  Second Owner      NaN     NaN   
31    Petrol  Individual       Manual  Second Owner      NaN     NaN   
78    Diesel  Individual       Manual   First Owner      NaN     NaN   
87    Diesel      Dealer       Manual   First Owner      NaN     NaN   
119   Diesel  Individual       Manual  Second Owner      NaN     NaN   
...      ...         ...          ...           ...      ...     ...   
7846  Diesel  Individual       Manual   First Owner      NaN     NaN   
7996  Petrol  Individual       Manual  Second Owner      NaN     NaN   
8009  Petrol  Individual       Manual  Second Owner      NaN     NaN   
8068  Diesel  Individual       Manual   First Owner      NaN     NaN   
8103  Petrol  Individual       Manual  Second Owner      NaN     NaN   

      max_power torque  seats torque_unit  
13          NaN    NaN    NaN        None  
31          NaN    NaN    NaN        None  
78          NaN    NaN    NaN        None  
87          NaN    NaN    NaN        None  
119         NaN    NaN    NaN        None  
...         ...    ...    ...         ...  
7846        NaN    NaN    NaN        None  
7996        NaN    NaN    NaN        None  
8009        NaN    NaN    NaN        None  
8068        NaN    NaN    NaN        None  
8103        NaN    NaN    NaN        None  

[234 rows x 14 columns]

In [52]:
data[data['torque_unit'].isna()]['torque'].unique()

array([nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800',
       '210 / 1900'], dtype=object)

In [53]:
data['torque_unit'].fillna('Nm',inplace=True)

In [55]:
string_example = '12.7@ 2,700(kgm@ rpm)'

In [56]:
string_example[0]

'1'

In [57]:
string_example[:4]

'12.7'

In [58]:
for i,j in enumerate(string_example):
  print(i,'번째 텍스트: ',j)

0 번째 텍스트:  1
1 번째 텍스트:  2
2 번째 텍스트:  .
3 번째 텍스트:  7
4 번째 텍스트:  @
5 번째 텍스트:   
6 번째 텍스트:  2
7 번째 텍스트:  ,
8 번째 텍스트:  7
9 번째 텍스트:  0
10 번째 텍스트:  0
11 번째 텍스트:  (
12 번째 텍스트:  k
13 번째 텍스트:  g
14 번째 텍스트:  m
15 번째 텍스트:  @
16 번째 텍스트:   
17 번째 텍스트:  r
18 번째 텍스트:  p
19 번째 텍스트:  m
20 번째 텍스트:  )


In [59]:
for i,j in enumerate(string_example):
  if j not in '0123456789':
    cut=i
    break

In [60]:
def split_num(x):
  x = str(x)
  for i,j in enumerate(x):
    if j not in '0123456789':
      cut = i
      break

  return x[:cut]

In [61]:
data['torque'] = data['torque'].apply(split_num)

In [63]:
data['torque'].head()

0    190
1    250
2     12
3     22
4     11
Name: torque, dtype: object

In [64]:
data['torque'] = data['torque'].astype('float64')

ValueError: could not convert string to float: ''

In [67]:
data['torque'] = data['torque'].replace('',np.nan)

In [68]:
data['torque'] = data['torque'].astype('float64')

In [69]:
data['torque'].head()

0    190.0
1    250.0
2     12.0
3     22.0
4     11.0
Name: torque, dtype: float64

In [70]:
#Nm = 9.8066 * kgm 중력가속도 곱하면 뉴턴 미터

In [71]:
def torque_trans(x):
  if x['torque_unit'] == 'kgm':
    return x['torque'] *9.8066
  else:
    return x['torque']

In [72]:
data['torque']=data.apply(torque_trans,axis=1)

In [73]:
data.drop('torque_unit',axis=1,inplace=True)

In [74]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage  engine  max_power  \
0  Individual       Manual   First Owner  0.318108  1248.0      74.00   
1  Individual       Manual  Second Owner  0.287384  1498.0     103.52   
2  Individual       Manual   Third Owner  0.220067  1497.0      78.00   
3  Individual       Manual   First Owner  0.312670  1396.0      90.00   
4  Individual       Manual   First Owner  0.200174  1298.0      88.20   

     torque  seats  
0  190.0000    5.0  
1  250.0000    5.0  
2  117.6792    5.0  
3  215.7452    5.0  
4  107.8726    5.0

k폴드 교차검증과 모델 생성

In [76]:
data['name']=data['name'].str.split(expand=True)[0]

In [77]:
data['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [78]:
#Land Rover
data['name'] = data['name'].replace('Land','Land Rover')

In [79]:
data.isna().mean()

name             0.000000
year             0.000000
selling_price    0.000000
km_driven        0.000000
fuel             0.000000
seller_type      0.000000
transmission     0.000000
owner            0.000000
mileage          0.027190
engine           0.027190
max_power        0.026575
torque           0.027313
seats            0.027190
dtype: float64

In [80]:
data.dropna(inplace=True)
len(data)

7906

In [81]:
data = pd.get_dummies(data,columns = ['name','fuel','seller_type','transmission','owner'],drop_first=True)

In [82]:
data.head()

year  selling_price  km_driven   mileage  engine  max_power    torque  \
0  2014         450000     145500  0.318108  1248.0      74.00  190.0000   
1  2014         370000     120000  0.287384  1498.0     103.52  250.0000   
2  2006         158000     140000  0.220067  1497.0      78.00  117.6792   
3  2010         225000     127000  0.312670  1396.0      90.00  215.7452   
4  2007         130000     120000  0.200174  1298.0      88.20  107.8726   

   seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0    5.0       False      False  ...         True     False        False   
1    5.0       False      False  ...         True     False        False   
2    5.0       False      False  ...        False     False         True   
3    5.0       False      False  ...         True     False        False   
4    5.0       False      False  ...        False     False         True   

   seller_type_Individual  seller_type_Trustmark Dealer  transmission_Manual  \
0                    True                         False                 True   
1                    True                         False                 True   
2                    True                         False                 True   
3                    True                         False                 True   
4                    True                         False                 True   

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                       False               False                 False   
1                       False                True                 False   
2                       False               False                 False   
3                       False               False                 False   
4                       False               False                 False   

   owner_Third Owner  
0              False  
1              False  
2               True  
3              False  
4              False  

[5 rows x 48 columns]

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(data.drop('selling_price',axis=1),data['selling_price'],test_size=0.2,random_state=100)

In [85]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [86]:
from sklearn.metrics import mean_squared_error
print('train mse: ',mean_squared_error(y_train,train_pred)**0.5)
print('test mse: ',mean_squared_error(y_test,test_pred)**0.5)

train mse:  57370.56092959647
test mse:  132555.78529685122


In [88]:
from sklearn.model_selection import KFold
data.reset_index(drop=True,inplace=True)
data

year  selling_price  km_driven   mileage  engine  max_power    torque  \
0     2014         450000     145500  0.318108  1248.0      74.00  190.0000   
1     2014         370000     120000  0.287384  1498.0     103.52  250.0000   
2     2006         158000     140000  0.220067  1497.0      78.00  117.6792   
3     2010         225000     127000  0.312670  1396.0      90.00  215.7452   
4     2007         130000     120000  0.200174  1298.0      88.20  107.8726   
...    ...            ...        ...       ...     ...        ...       ...   
7901  2013         320000     110000  0.230014  1197.0      82.85  113.0000   
7902  2007         135000     119000  0.228385  1493.0     110.00  235.3584   
7903  2009         382000     120000  0.262371  1248.0      73.90  190.0000   
7904  2013         290000      25000  0.320419  1396.0      70.00  140.0000   
7905  2013         290000      25000  0.320419  1396.0      70.00  140.0000   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0       5.0       False      False  ...         True     False        False   
1       5.0       False      False  ...         True     False        False   
2       5.0       False      False  ...        False     False         True   
3       5.0       False      False  ...         True     False        False   
4       5.0       False      False  ...        False     False         True   
...     ...         ...        ...  ...          ...       ...          ...   
7901    5.0       False      False  ...        False     False         True   
7902    5.0       False      False  ...         True     False        False   
7903    5.0       False      False  ...         True     False        False   
7904    5.0       False      False  ...         True     False        False   
7905    5.0       False      False  ...         True     False        False   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                       True                         False   
1                       True                         False   
2                       True                         False   
3                       True                         False   
4                       True                         False   
...                      ...                           ...   
7901                    True                         False   
7902                    True                         False   
7903                    True                         False   
7904                    True                         False   
7905                    True                         False   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                    True                       False               False   
1                    True                       False                True   
2                    True                       False               False   
3                    True                       False               False   
4                    True                       False               False   
...                   ...                         ...                 ...   
7901                 True                       False               False   
7902                 True                        True               False   
7903                 True                       False               False   
7904                 True                       False               False   
7905                 True                       False               False   

      owner_Test Drive Car  owner_Third Owner  
0                    False              False  
1                    False              False  
2                    False               True  
3                    False              False  
4                    False              False  
...                    ...                ...  
7901                 False              False  
7902                 False              False  
7903  

In [91]:
kf = KFold(n_splits = 5)

In [92]:
X = data.drop('selling_price',axis=1)
y = data['selling_price']

In [93]:
for i,j in kf.split(X):
  print(i,j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]


In [94]:
for train_index,test_index in kf.split(X):
  X_train,X_test = X.loc[train_index],X.loc[test_index]
  y_train,y_test = y[train_index],y[test_index] # 1줄이어서 loc 안사용

In [95]:
train_rmse_total = []
test_rmse_total = []

In [97]:
for train_index,test_index in kf.split(X):
  X_train,X_test = X.loc[train_index],X.loc[test_index]
  y_train,y_test = y[train_index],y[test_index]

  model = RandomForestRegressor()
  model.fit(X_train,y_train)
  train_pred = model.predict(X_train)
  test_pred = model.predict(X_test)

  train_mse = mean_squared_error(y_train,train_pred)**0.5
  test_mse = mean_squared_error(y_test,test_pred)**0.5

  train_rmse_total.append(train_mse)
  test_rmse_total.append(test_mse)

In [98]:
train_rmse_total

[50786.322644382206,
 52856.374087024924,
 55746.11004566838,
 52859.440117672755,
 53554.313113485274]

In [99]:
print('train_rmse:', sum(train_rmse_total)/ 5)

train_rmse: 53160.512001646704
